services:
  postgres:
    image: pgvector/pgvector:pg17
    shm_size: 128mb
    ports:
      - 5432:5432
    volumes:
      - /users/venthe/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080