[default]
log_level=info
log_path=

[openvoice]
use_gpu=true
; EN, EN_V2, EN_NEWEST, FR, JP, ES, ZH, KR
language_model=EN_NEWEST
speaker_key=EN-Newest
speed=1.0
sdp_ratio=0.2
noise_scale=0.6
noise_scale_w=0.8
quiet=False

[openvoice-embedding]
converter_path=model/converter/
speaker_model=model/base_speakers/ses/en-default.pth
embedding_model=model/embedding/checkpoint.pth
tau=0.3

[openvoice-embedding-training]
use_vad=True

[server]
port=5000
host=0.0.0.0
debug=false

; [default]
; log_level=info
; log_path=

; [model]
; model_path=model
; model_name=medium.en
; initial_prompt=
; use_gpu=true
; temperature=0
; hallucination_silence_threshold=1
; language=en